version: '3'
services:
  spot_viewpoint_planning:
    image: spot_viewpoint_planning:0.0.1
    network_mode: "host"
    container_name: spot_viewpoint_planning
    environment:
      - "ROS_HOSTNAME=${ROS_HOSTNAME}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
    volumes:
      - ./../src:/workspace/src
    command:  roscore
