version: '3'
services:
  spot_viewpoint_planning:
    image: spot_viewpoint_planning:0.0.1
    network_mode: "host"
    container_name: spot_viewpoint_planning
    environment:
      - "ROS_HOSTNAME=${ROS_HOSTNAME}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
    volumes:
      - ./../src:/workspace/src
    command:  bash -c "source devel/setup.bash && roslaunch spot_viewpoint_planning spot_viewpoint_planning.launch"

  april_tag_detection:
    image: spot_viewpoint_planning:0.0.1
    network_mode: "host"
    container_name: april_tag_detection
    environment:
      - "ROS_HOSTNAME=${ROS_HOSTNAME}"
      - "ROS_MASTER_URI=${ROS_MASTER_URI}"
    volumes:
      - ./../src:/workspace/src
    command:  bash -c "source devel/setup.bash && roslaunch apriltag_ros continuous_detection.launch"
